export const alumni = [
  {
    id: 1,
    name: "Alice",
    description: "Alice, a highly skilled software developer, passionate about robust solutions and experienced in diverse technologies.",
    course: "Computer Science",
    img: "./assets/alumni/alice.jpg",
  },
  {
    id: 2,
    name: "Bob",
    description: "Bob, a talented web developer known for creating stunning, user-friendly websites with expertise in frontend and backend technologies.",
    course: "Web Development",
    img: "./assets/alumni/bob.jpg",
  },
  {
    id: 3,
    name: "Charlie",
    description: "Charlie, a skilled backend developer, excels in building software systems and optimizing server-side applications.",
    course: "Software Engineering",
    img: "./assets/alumni/charlie.jpg",
  },
  {
    id: 4,
    name: "Berke",
    description: "Meet Berke, the enigmatic culinary genius known as Der Gerät, mastering the art of kebab preparation.",
    course: "Professional Doenner Consultant",
    img: "./assets/alumni/berke.jpg",
  },
  {
    id: 5,
    name: "Eva",
    description: "Eva, a proficient DevOps engineer, specializes in automating and optimizing development and ensuring efficient software delivery.",
    course: "DevOps and Cloud Computing",
    img: "./assets/alumni/eva.jpg",
  },
  {
    id: 6,
    name: "Frank",
    description: "Frank, a seasoned software engineer, expert in building complex, scalable software systems with a deep understanding of design principles.",
    course: "Computer Science",
    img: "./assets/alumni/frank.jpg",
  },
  {
    id: 7,
    name: "Grace",
    description: "Grace, a frontend developer known for creating visually appealing, responsive user interfaces and expertise in web development.",
    course: "Web Development",
    img: "./assets/alumni/grace.jpg",
  },
  {
    id: 8,
    name: "Hannah",
    description: "Hannah, a dedicated security analyst, safeguards digital assets and data, with a keen eye for identifying vulnerabilities.",
    course: "Cybersecurity",
    img: "./assets/alumni/hannah.jpg",
  },
  {
    id: 9,
    name: "Isaac",
    description: "Isaac, a versatile full-stack developer, handles both frontend and backend tasks with a holistic approach to software solutions.",
    course: "Software Engineering",
    img: "./assets/alumni/isaac.jpg",
  },
];
